[global]
keep_alive = 0
workers = 128
log = "normal"
secret_key = "eZ8J/CJ2LuGx/lI481zxWK/3BnIy+LYjhwSZnKkdrRY="
port = 4242

[global.databases]
pg_diesel = { url = "postgres://diesel:diesel@postgres:5432/diesel" }