version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: diesel
      POSTGRES_PASSWORD: diesel
      POSTGRES_DB: diesel
      PGDATA: /data/postgres
    volumes:
      - ./data/:/data:rw
    command: postgres -c listen_addresses='*'
#    ports:
#      - 5469:5432

  activitytracker:
    build: .
    depends_on:
      - postgres
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    environment:
      DATA_DIR: /data/imgs/
    # Define the port mapping (external:internal port)
    ports:
      - 4242:8000
    restart: always

volumes:
  postgres-data: