version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: diesel
      POSTGRES_PASSWORD: diesel
      POSTGRES_DB: diesel
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5469:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: richard@enoflag.de
      PGADMIN_DEFAULT_PASSWORD: enoflag
    restart: unless-stopped

  activitytracker:
    build: .
    depends_on:
      - postgres
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    # Define the port mapping (external:internal port)
    ports:
      - 4242:8000

volumes:
  postgres-data: