version: '3'
services:
  # Give your container proper names!
  activitytracker-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 2424:3031
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=activitytracker-mongo
     - MONGO_PORT=27017
     - MONGO_USER=activitytracker_checker
     - MONGO_PASSWORD=activitytracker_checker

  # The python checkerlib requires a mongo db!
  activitytracker-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: activitytracker_checker
      MONGO_INITDB_ROOT_PASSWORD: activitytracker_checker